### ISSUE TITLE
dnf install contour-terminal on Fedora 38 missing libicu 67 (version installed on the OS is icu71)

### ISSUE THREAD

**Issue by nurettin** [contour-terminal/contour#1241] opened 2023-10-09 09:10 UTC
### Contour Terminal version

0.3.12.262 release 1.fc38 contour-terminal-0.3.12.262-1.fc38.src.rpm

### Installer source

something else (please specify below)

### Operating System

Fedora 38

### Architecture

x86-64

### Steps to reproduce

install fresh fedora 38
sudo dnf install contour-terminal

run contour
contour --version
contour: error while loading shared libraries: libicui18n.so.67: cannot open shared object file: No such file or directory

### Expected Behavior

awesome modern terminal with cool graphics shows up 

### Actual Behavior

awesome modern terminal with cool graphics does not show up 

### Additional notes

I have icu71, I tried symlinking but it complained about elf format 
thank you

**Comment by Yaraslaut** [comment] 2023-10-09 09:54
I hope @topazus can help us out here in updating fedora package

**Comment by topazus** [comment] 2023-10-09 15:48
> contour: error while loading shared libraries: libicui18n.so.67: cannot open shared object file: No such file or directory

I also have no clue, which is about the reason why contour-terminal load libicui18n.so.67 , since the libicu package version on Fedora 38 cannot be 67 when building contour-terminal 0.3.12.262 , see: https://bodhi.fedoraproject.org/updates/?search=libicu&releases=F38

**Comment by Utkarsh-khambra** [comment] 2023-10-09 16:45
This is ldd output for rpm directly downloaded from [here](https://koji.fedoraproject.org/koji/buildinfo?buildID=2207343).
```
utkarsh@fedora:/tmp/usr/bin$ ldd contour |grep icu
        libicui18n.so.72 => /lib64/libicui18n.so.72 (0x00007f9abb400000)
        libicuuc.so.72 => /lib64/libicuuc.so.72 (0x00007f9abb000000)
        libicudata.so.72 => /lib64/libicudata.so.72 (0x00007f9ab8a00000)

```
Maybe it's something to do with the fact that it's a fresh install of fedora38, could you please update the system first and then try and install contour again. Maybe that would work.

**Comment by Utkarsh-khambra** [comment] 2023-10-09 17:16
I tested this with freshly installed fedora 38 in a VM, and I can't repro this.

**Comment by Yaraslaut** [comment] 2023-10-10 16:26
Seems issue does not exist, since can not be reproducible, so I'm closing this issue.

**Closed by Yaraslaut** 2023-10-10 16:26 UTC
Labels: bug
