### ISSUE TITLE
Problems with unicode character showing up when starting with this terminal(not when connected to attached tmux session)

### ISSUE THREAD

**Issue by mTvare6** [contour-terminal/contour#388] opened 2021-08-10 14:25 UTC
## Description

Some unicode characters don't show up when launching this terminal on macos, but work when connected via tmux on other session

## Environment

- Contour Version or Git commit hash: 0.2.0 1332(prerelease)
- Operating System (name / distribution / version): macOS 11.3.1
- Contour configuration: can reproduce with stock config
- TERM environment variable: xterm-256color
- Compiler version: didn't compile from source

## Steps to Reproduce

Open the terminal. Here a detailed video

https://user-images.githubusercontent.com/57838468/128884455-c6ed4452-963e-4693-a0ce-11f0df4a7a60.mov

**Comment by christianparpart** [comment] 2021-08-16 10:06
Current behavior (frame excerpt from the video):

![image](https://user-images.githubusercontent.com/56763/129546506-9a149e93-8b44-40fc-b3fe-a2083769a851.png)

Expected behavior (frame excerpt from the video):

![image](https://user-images.githubusercontent.com/56763/129546765-f9355fea-c80e-423e-8b89-1af16f714436.png)

@mTvare6 I just merged some font fallback related changes (and more) to master. So it might be interesting to know if that fixed it. I sadly quite much doubt that and instead think that your problem might be related to your locale settings.

Would you mind giving that a try? Check the output of  `locale and `echo $LANG`output and see if they differ when being in contour + no tmux and contour + inside tmux?

Mind, Contour currently only supports UTF-8, none of the other legacy encodings, such as iso-8859-15 etc. I also don't think it's actually worth implementing on new terminal implementations. I'm not hard-coded on that way of thinking. Maybe some other users/devs have an interesting insight on that point of view. ;)

**Comment by uspasojevic96** [comment] 2021-08-16 10:20
@christianparpart default locale for macOS is `C` and LANG is unset:

```
~ via ⬢ v14.16.0 via 🐘 v7.3.24 via 𝗥 v1.52.1
➜ locale
LANG=""
LC_COLLATE="C"
LC_CTYPE="UTF-8"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=
```

**Comment by christianparpart** [comment] 2021-08-17 08:08
@mTvare6 

Try that one:  https://github.com/contour-terminal/contour/releases/tag/v0.2.0.171_rc2 

And if you don't mind, please send me the `locale` output from outside *and* inside tmux, just like @uspasojevic96 did (I try to repro that though, too).

**Comment by mTvare6** [comment] 2021-08-17 11:57
In tmux, opened with contour
```
LANG=""
LC_COLLATE="C"
LC_CTYPE="C"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=
```
In tmux, open with iTerm2
```
LANG=""
LC_COLLATE="C"
LC_CTYPE="UTF-8"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=
```

**Comment by christianparpart** [comment] 2024-01-07 01:08
I am closing this issue, because I seem not to be able to get to reproduce it. It also is very long ago and we had no similar reports.

@mTvare6 if you happen to still see them, please reopen this issue and we then will probably need more input with a fresh look on it.

**Closed by christianparpart** 2024-01-07 01:08 UTC
Labels: bug, VT: rasterizer, fonts, blocker
