### ISSUE TITLE
The terminal does not appear.

### ISSUE THREAD

**Issue by mantarimay** [contour-terminal/contour#1397] opened 2024-01-01 02:15 UTC
### Contour Terminal version

0.4.1.6292

### Installer source

Github: source code cloned

### Operating System

openSUSE Tumbleweed

### Architecture

x86-64

### Other Software

libunicode version        : 0.4.0-21.1
boxed-cpp-devel version        : 1.1.0-4.2
gnome-shell version        : 45.0+172 git.1dda3393-220.1
labwc version        : 0.7.0+28 git.21234a5-33.1

### Steps to reproduce

1. upgrade from 0.3 to 0.4
2. open terminal 
3. and then terminal does not appear.

### Expected Behavior

Terminal appears and is functional, like version 0.3.

### Actual Behavior

I tried version 0.3.12.262 and had no problem, but after upgrading to 0.4, terminal did not appear.

```
Warning: QQmlApplicationEngine failed to load component ((null):0, (null))
Warning: qrc:/contour/ui/main.qml: module "org.kde.desktop" is not installed (qrc:/contour/ui/main.qml:4294967295, (null))
```

![Screenshot from 2024-01-01 08-45-56](https://github.com/contour-terminal/contour/assets/42089808/9ad101ec-1848-458c-ae4f-f2ab2909ee4a)

### Additional notes

tested on wayland at gnome-shell & labwc (wlroots). 

I wish I could push and update to the main repo on openSUSE, but sadly, it's not open properly.

Build info:
https://build.opensuse.org/project/show/home:mantarimay:branches:X11:terminals

**Comment by Yaraslaut** [comment] 2024-01-01 07:26
Can you run `contour debug all` and share the output?

**Comment by christianparpart** [comment] 2024-01-01 12:47
```
Warning: QQmlApplicationEngine failed to load component ((null):0, (null))
Warning: qrc:/contour/ui/main.qml: module "org.kde.desktop" is not installed (qrc:/contour/ui/main.qml:4294967295, (null))
```
this is the part I find interesting, or most concerning. I am not sure why it even thinks that `org.kde.desktop` should be a thing for Contour. 🤔 None of these warnings should have been shown. 🤔

**Comment by christianparpart** [comment] 2024-01-01 13:13
Hey, i'm trying to build on openSUSE Tumbleweed myself and realized that our install-deps.sh script is still only installing qt5 dependencies. How did you build it for SuSE? Using Qt5 or Qt6 dependencies? What are you dependencies that you used? (I'm trying to get it running on a local openSuSE VM myself :)

**Comment by christianparpart** [comment] 2024-01-01 16:14
I'm having issues finding the package that provides `QOpenGLFunctions_3_3_Core` for Qt 6. I'll be creating a PR ASAP to fix at least the dev install way, `scripts/install-deps.sh`, to also support building using Qt 6.

**Comment by christianparpart** [comment] 2024-01-01 17:16
thx for your quick response, @mantarimay. yeah, i know about OBS having hard-moved to qt6. I'd prefer that too, but we still need to somehow support Ubuntu 18.04 and 20.04 (wich both don't come with Qt 6). We try to default and build with Qt 6 where-ever possible. Also, we have some features that only work if built with qt6 (like color schemes automatically adapting to dark/light mode switching).

> `BuildRequires:  Catch2-2-devel`

that should be at least Catch2 version 3 (3.4) with Contour >= 0.4.0 (0.4.1 as of last night)

> `%{_datadir}/terminfo/c/contour*`

As of Contour >= 0.4.1, we've dropped `contour-latest`, as we try hard to not require any changes to it at all. There's no need to provide that now anymore :)

> `% changelog`

Not sure if this line is addressing it, but we have the changelog embedded into the metainfo.xml. If not, you could use xmllint to extract the changelog info as well. That's what we do for the release CI :)

**Comment by christianparpart** [comment] 2024-01-01 17:22
> `Recommends:     kf5-filesystem`
I'd highly recommend to add libsixel-tools to it (is it called like this?) (https://github.com/libsixel/libsixel),

because of the CLI tool `img2sixel`, which can be used to display Sixel images in Contour terminal.

**Comment by christianparpart** [comment] 2024-01-01 19:54
@mantarimay I know this is the **worst** part to point out at potential bugs in the openSuSE packaging, but I think there's a problem with `qt6-opengl-devel` package for ARM64 (AArch64) architectures.

Somehow somebody believed that on ARM64 one only needs OpenGL ES, and thus, the above package does not provide any other GL function headers for qt6 (qt5-opengl-devel does provide them btw). I am on an ARM64 laptop (Apple M1) on various Linux distros. So far openSuSE (Tumbleweed) is the first one that does not provide more headers, such as the one we need `QOpenGLFunctions_3_3_Core`.

Can you maybe point me to the place were I could report it in a way it is heard, or you could drop that info to the relevant people? (sorry for the comms abuse :) )

I'll try to spin up a SuSE distro on my x86-64 desktop pc once i'm near it to repro your findings :)

**Comment by christianparpart** [comment] 2024-01-01 20:21
@Marenz You have Contour build from source on openSuSE Tumbleweed. Do you happen to remember what you added (dependencies installed) to get it working with Qt 6?

**Comment by uunnxx** [comment] 2024-01-02 00:34
Hi there!
I've the same issues... I had running contour, but tried to upgrade and downloaded last `deb` file.

```
Notice: The following will be installed to satisfy contour:
  libqt6multimedia6
===============================================================================================================
 Installing
===============================================================================================================
  Package:                             Version:                                                         Size:
  libqt6multimedia6                    6.4.2-4                                                         525 KB

===============================================================================================================
 Upgrading
===============================================================================================================
  Package:                             Old Version:            New Version:                             Size:
  contour                              0.3.11.258              0.4.1.6292                                7 KB

```

and after upgrading
![image](https://github.com/contour-terminal/contour/assets/6236057/5646b11b-15ef-469e-9c94-5a9da3de9165)


`contour debug all`:

```
[2024-01-02 00:33:06.336724232.336724] [config] Loading configuration from file: /home/baka/.config/contour/contour.yml
[2024-01-02 00:33:06.339004619.339004] [config] Missing key .logging.enabled. Using default: false.
[2024-01-02 00:33:06.339020640.339020] [config] Missing key .logging.file. Using default: "".
[2024-01-02 00:33:06.339121801.339121] [config] Missing key background_image.path. Using default: "".
[2024-01-02 00:33:06.339150345.339150] [config] Missing key .shell. Using default: "".
[2024-01-02 00:33:06.339194659.339194] [config] Missing key .refresh_rate. Using default: 0.
[2024-01-02 00:33:06.339205059.339205] [config] Missing key .size_indicator_on_resize. Using default: true.
[2024-01-02 00:33:06.339241738.339241] [config] Defaulting TERM to contour.
[2024-01-02 00:33:06.339250284.339250] [config] Missing key .margins.horizontal. Using default: 0.
[2024-01-02 00:33:06.339255995.339255] [config] Missing key .margins.vertical. Using default: 0.
[2024-01-02 00:33:06.339270092.339270] [config] Missing key permissions.display_host_writable_statusline. Using default: ask.
[2024-01-02 00:33:06.339309246.339309] [config] Missing key .option_as_alt. Using default: false.
[2024-01-02 00:33:06.339364180.339364] [config] Missing key status_line.position. Using default: none.
[2024-01-02 00:33:06.339371544.339371] [config] Missing key status_line.sync_to_window_title. Using default: false.
[2024-01-02 00:33:06.339377836.339377] [config] Missing key .bell.sound. Using default: default.
[2024-01-02 00:33:06.339383998.339383] [config] Missing key .bell.alert. Using default: false.
[2024-01-02 00:33:06.339389909.339389] [config] Missing key .bell.volume. Using default: 0.
[2024-01-02 00:33:06.339673045.339673] [config] Superfluous config key found: profiles.main.font.dpi_scale
Warning: QQmlApplicationEngine failed to load component ((null):0, (null))
Warning: qrc:/contour/ui/main.qml:6:1: module "Qt.labs.platform" is not installed (qrc:/contour/ui/main.qml:6, (null))
Warning: qrc:/contour/ui/main.qml:5:1: module "QtQuick.Window" is not installed (qrc:/contour/ui/main.qml:5, (null))
Warning: qrc:/contour/ui/main.qml:4:1: module "QtQuick.Layouts" is not installed (qrc:/contour/ui/main.qml:4, (null))
Warning: qrc:/contour/ui/main.qml:3:1: module "QtQuick.Controls" is not installed (qrc:/contour/ui/main.qml:3, (null))
Warning: qrc:/contour/ui/main.qml: module "QtQml.WorkerScript" is not installed (qrc:/contour/ui/main.qml:4294967295, (null))
Warning: qrc:/contour/ui/main.qml:6:1: module "Qt.labs.platform" is not installed (qrc:/contour/ui/main.qml:6, (null))
Warning: qrc:/contour/ui/main.qml:5:1: module "QtQuick.Window" is not installed (qrc:/contour/ui/main.qml:5, (null))
Warning: qrc:/contour/ui/main.qml:4:1: module "QtQuick.Layouts" is not installed (qrc:/contour/ui/main.qml:4, (null))
Warning: qrc:/contour/ui/main.qml:3:1: module "QtQuick.Controls" is not installed (qrc:/contour/ui/main.qml:3, (null))
Warning: qrc:/contour/ui/main.qml: module "QtQml.WorkerScript" is not installed (qrc:/contour/ui/main.qml:4294967295, (null))
Warning: qrc:/contour/ui/main.qml:6:1: module "Qt.labs.platform" is not installed (qrc:/contour/ui/main.qml:6, (null))
Warning: qrc:/contour/ui/main.qml:5:1: module "QtQuick.Window" is not installed (qrc:/contour/ui/main.qml:5, (null))
Warning: qrc:/contour/ui/main.qml:4:1: module "QtQuick.Layouts" is not installed (qrc:/contour/ui/main.qml:4, (null))
Warning: qrc:/contour/ui/main.qml:3:1: module "QtQuick.Controls" is not installed (qrc:/contour/ui/main.qml:3, (null))
Warning: qrc:/contour/ui/main.qml: module "QtQml.WorkerScript" is not installed (qrc:/contour/ui/main.qml:4294967295, (null))
Warning: qrc:/contour/ui/main.qml:6:1: module "Qt.labs.platform" is not installed (qrc:/contour/ui/main.qml:6, (null))
Warning: qrc:/contour/ui/main.qml:5:1: module "QtQuick.Window" is not installed (qrc:/contour/ui/main.qml:5, (null))
Warning: qrc:/contour/ui/main.qml:4:1: module "QtQuick.Layouts" is not installed (qrc:/contour/ui/main.qml:4, (null))
Warning: qrc:/contour/ui/main.qml:3:1: module "QtQuick.Controls" is not installed (qrc:/contour/ui/main.qml:3, (null))
Warning: qrc:/contour/ui/main.qml: module "QtQml.WorkerScript" is not installed (qrc:/contour/ui/main.qml:4294967295, (null))
Warning: qrc:/contour/ui/main.qml:6:1: module "Qt.labs.platform" is not installed (qrc:/contour/ui/main.qml:6, (null))
Warning: qrc:/contour/ui/main.qml:5:1: module "QtQuick.Window" is not installed (qrc:/contour/ui/main.qml:5, (null))
Warning: qrc:/contour/ui/main.qml:4:1: module "QtQuick.Layouts" is not installed (qrc:/contour/ui/main.qml:4, (null))
Warning: qrc:/contour/ui/main.qml:3:1: module "QtQuick.Controls" is not installed (qrc:/contour/ui/main.qml:3, (null))
Warning: qrc:/contour/ui/main.qml: module "QtQml.WorkerScript" is not installed (qrc:/contour/ui/main.qml:4294967295, (null))
```

**Comment by christianparpart** [comment] 2024-01-02 06:41
Hey @uunnxx . I am really sorry for this experience. There seems to be dependencies missing. We are going to fix this ASAP. -- if nobody was faster, I will be trying to fix that after I am back from work, tonight . Sorry for the inconveniences .

**Comment by uunnxx** [comment] 2024-01-02 08:32
@christianparpart after installing these dependencies, I've successfully running `contour`:

```
qml6-module-qt-labs-platform
qml6-module-qtquick-window
qml6-module-qtquick-layouts
qml6-module-qtquick-controls
qml6-module-qtqml-workerscript
qml6-module-qtquick-templates
qml6-module-qtmultimedia
qml6-module-qt5compat-graphicaleffects
qt6-5compat-dev  # not sure about this one. Maybe installing previous one e.g. `qml6-module-qt5compat-graphicaleffects` is enough.   
```

**Comment by christianparpart** [comment] 2024-01-03 20:46
@uunnxx what distribution are you on? I could not find a `qt6-5compat-dev` on Ubuntu 22.04, but rather `libqt6core5compat6-dev`. If I am not mistaken (@Yaraslaut?) we'll need qt5 compat mode for qt6 build, at least for the time being still.

**Comment by Yaraslaut** [comment] 2024-01-03 20:50
> @uunnxx what distribution are you on? I could not find a `qt6-5compat-dev` on Ubuntu 22.04, but rather `libqt6core5compat6-dev`. If I am not mistaken (@Yaraslaut?) we'll need qt5 compat mode for qt6 build, at least for the time being still.

No, this module is not for qt5, this is due to lack of some features from qt5 in qt6 qml, Blur for instance

**Comment by christianparpart** [comment] 2024-01-03 22:11
@mantarimay Hey, my linked PR #1399 seems to work for Ubuntu 22.04 packaging. Looking at the diff, maybe that helps creating a .rpm package for SuSE Tumbleweed as well?

Is there anything we can do on our end to ease packaging?

Mind, with Contour 0.4, we've transitioned from from Qt Widgets (default Qt 5) to Qt QML (default Qt 6). This is rumbling, and I hope we can ease the inconveniences to a minimum to all as much as possible.

**Comment by christianparpart** [comment] 2024-01-03 22:12
@uunnxx your comment aboved helped me A LOT! Many thanks for that. :1st_place_medal:

**Comment by christianparpart** [comment] 2024-01-03 23:14
@mantarimay ok i think i've found the last missing dependencies on SuSE Linux for Contour >= 0.4, which are:

- qt6-qt5compat-imports
- qt6-multimedia-imports

So in total (in our install-deps.sh script, for quick building from source), we have the following section for SuSE identified systems:

https://github.com/contour-terminal/contour/blob/1df9f704afaaea36f66d5b17d0007d09f9a496d5/scripts/install-deps.sh#L435-L448

**Comment by christianparpart** [comment] 2024-01-04 08:46
Good morning. @mantarimay when you confirm, that you've got it working on the SuSE side, I think we can close this ticket. No hurries though, take your time :)

**Comment by christianparpart** [comment] 2024-01-04 21:56
@mantarimay I really wonder where this `"org.kde.desktop"` is coming from. 🤔 hmmmmm

**Comment by Marenz** [comment] 2024-01-05 12:55
> @Marenz You have Contour build from source on openSuSE Tumbleweed. Do you happen to remember what you added (dependencies installed) to get it working with Qt 6?

not specifically no, as it was a constant add this delete this etc so at the end I had no idea which part was really required. I can check what packages are installed now at least, but which ones of those are actually required I can't say. Let me know if you want it (as it is on an other computer I have to boot then)

**Comment by christianparpart** [comment] 2024-01-05 14:38
I think it's not a package issue per se. we should try to figure out why we see this one warning there, stating `module "org.kde.desktop" is not installed`. We have no KDE specific code at all. 🤔 Maybe one (having that issue) could start contour with Qt logging enabled. I'll try to setup a fresh openSuSE over the weekend and try to figure out how to build the .spec file (@mantarimay would you mind pointing us to the relevant other .spec files, e.g. for libunicode, such that we can repro building the rpm's locally?)

**Comment by Yaraslaut** [comment] 2024-01-06 10:50
I compiled contour on opensuse from (https://github.com/contour-terminal/contour/pull/1399)  and everything works for me

**Comment by christianparpart** [comment] 2024-01-06 17:39
> I compiled contour on opensuse from (https://github.com/contour-terminal/contour/pull/1399) and everything works for me

@Yaraslaut I think we need to repro that by using @mantarimay's .spec files - and these on a fresh SuSE image :)

**Comment by Yaraslaut** [comment] 2024-01-10 16:09
@mantarimay  can you please help me a bit, how to test this `.spec` files locally?

**Comment by kierun** [comment] 2024-01-17 20:18
I ran into a similar issue on Fedora 39:

```bash
√ ; contour debug all
[2024-01-17 20:16:57.686968366.686968] [config] Loading configuration from file: /home/yg/.config/contour/contour.yml
[2024-01-17 20:16:57.689668714.689668] [config] Missing key .logging.enabled. Using default: false.
[2024-01-17 20:16:57.689676344.689676] [config] Missing key .logging.file. Using default: "".
[2024-01-17 20:16:57.689755864.689755] [config] Missing key background_image.path. Using default: "".
[2024-01-17 20:16:57.689784594.689784] [config] Missing key .shell. Using default: "".
[2024-01-17 20:16:57.689816535.689816] [config] Missing key .refresh_rate. Using default: 0.
[2024-01-17 20:16:57.689850435.689850] [config] Defaulting TERM to contour.
[2024-01-17 20:16:57.698985173.698985] [gui.display] Color theme mode at startup: Light
Warning: QQmlApplicationEngine failed to load component ((null):0, (null))
Warning: qrc:/contour/ui/main.qml:30:5: Type Terminal unavailable (qrc:/contour/ui/main.qml:30, (null))
Warning: qrc:/contour/ui/Terminal.qml:8:1: module "Qt5Compat.GraphicalEffects" is not installed (qrc:/contour/ui/Terminal.qml:8, (null))
```

```bash
 ; sudo dnf5 install contour-terminal
Updating and loading repositories:
 Fedora 39 - x86_64 - Updates                                                   100% | 113.2 KiB/s |  22.0 KiB |  00m00s
Repositories loaded.
Package                                 Arch       Version                                 Repository               Size
Installing:
 contour-terminal                       x86_64     0.4.1.6292-1.fc39                       updates               3.1 MiB
```

**Comment by Yaraslaut** [comment] 2024-01-17 20:38
Looks like fedora package is missing some dependencies, can you please check if installing  [qt6-qt5compat](https://src.fedoraproject.org/rpms/qt6-qt5compat)  package will resolve this issue for you @kierun?  So @topazus  can update package to fix it

**Comment by topazus** [comment] 2024-01-18 05:52
> Looks like fedora package is missing some dependencies, can you please check if installing [qt6-qt5compat](https://src.fedoraproject.org/rpms/qt6-qt5compat) package will resolve this issue for you @kierun? So @topazus can update package to fix it

So qt6-qt5compat is runtime dependency?

**Comment by kierun** [comment] 2024-01-18 08:51
> [qt6-qt5compat](https://src.fedoraproject.org/rpms/qt6-qt5compat)

@topazus , @Yaraslaut I installed this package and `contour` launched successfully. I am getting this:

```
Warning: Couldn't load VAAPI library ((null):0, (null))
```

But it does not seem to affect the terminal at all.

**Comment by cqexbesd** [comment] 2024-01-18 17:52
@kierun IIUC that message is because QT is trying to use hardware acceleration but you are probably missing a(nother) library. Apart from performance I don't think it will affect anything - I only just silenced a similar warning on my system today - yet to notice any performance improvements.

**Comment by kierun** [comment] 2024-01-18 18:20
@cqexbesd Thanks for the help. Any chance you can remember which package that is?

**Comment by cqexbesd** [comment] 2024-01-18 20:06
> @cqexbesd Thanks for the help. Any chance you can remember which package that is?

Everything I know is from https://wiki.archlinux.org/title/Hardware_video_acceleration so I think it depends on your hardware.

**Comment by Yaraslaut** [comment] 2024-01-20 15:36
@mantarimay so few packages are missing as a dependency :( i managed to open contour after installing [qt6-qt5compat-imports](https://opensuse.pkgs.org/15.5/opensuse-oss-x86_64/qt6-qt5compat-imports-6.4.2-150500.1.15.aarch64.rpm.html) and [qt6-multimedia-imports](https://opensuse.pkgs.org/tumbleweed/opensuse-oss-x86_64/qt6-multimedia-imports-6.6.0-1.1.x86_64.rpm.html)

**Comment by christianparpart** [comment] 2024-01-20 17:11
> @mantarimay so few packages are missing as a dependency :( i managed to open contour after installing [qt6-qt5compat-imports](https://opensuse.pkgs.org/15.5/opensuse-oss-x86_64/qt6-qt5compat-imports-6.4.2-150500.1.15.aarch64.rpm.html) and [qt6-multimedia-imports](https://opensuse.pkgs.org/tumbleweed/opensuse-oss-x86_64/qt6-multimedia-imports-6.6.0-1.1.x86_64.rpm.html)

I just checked. We've added these already to our install-deps.sh script in 1df9f704a (Jan 4th '24).

@mantarimay: As soon as you confirm that you CAN build a package for SuSE Linux again, we'll be releasing 0.4.2. So once confirmed by you, you may want to wait a very little bit and go straight for 0.4.2 then. It will contain bug fixes only (quite important ones IMHO), if you don't mind.

Many thanks, and sorry for the inconveniences. :)

**Comment by christianparpart** [comment] 2024-01-20 19:45
@mantarimay i'd like your machine to work though, as well...

**Comment by Yaraslaut** [comment] 2024-01-27 09:09
@mantarimay  any updates?

**Comment by Yaraslaut** [comment] 2024-02-04 12:40
> @Yaraslaut I am glad now that I know the problem. It's because I use `QT_QPA_PLATFORMTHEME=gnome`. ![Screenshot from 2024-02-04 19-27-47](https://private-user-images.githubusercontent.com/42089808/302102581-78aaa9d6-5fb4-4320-9c89-7ffd2261bb0f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwNTA1NTQsIm5iZiI6MTcwNzA1MDI1NCwicGF0aCI6Ii80MjA4OTgwOC8zMDIxMDI1ODEtNzhhYWE5ZDYtNWZiNC00MzIwLTljODktN2ZmZDIyNjFiYjBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA0VDEyMzczNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWViMDQ5OTllMTljNzRlMjRjZmYxMzBmYTIwOWNjOTRlODRlNzdjYmVhNWI3OGRiODBjZDNkMGJkOGQxODRkMmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-SQhcF0JPotJx_z9xnzQZG5WiHqVycx9Y7Vr22PkgqU)

Oh, great that everything is working now :)

**Closed as completed** 2024-02-04 12:52 UTC

**Comment by christianparpart** [comment] 2024-02-04 19:37
@mantarimay FYI: I sadly need to release again, because last night release contains a mutex thread locking condition. So I'll release now, containing only the fix, but I sadly have to bump the numbers for this, to 0.4.3

**Comment by sameepvicky** [comment] 2025-08-15 01:58
Perhaps, try setting the environment variable:
QT_QUICK_CONTROLS_STYLE=“org.kde.desktop”

https://discuss.kde.org/t/module-org-kde-kirigami-is-not-installed/1233/11?u=sameepvicky
