### ISSUE TITLE
allow sixels to expand beyond 800x600

### ISSUE THREAD

**Issue by dankamongmen** [contour-terminal/contour#422] opened 2021-09-26 12:19 UTC
## Description

I notice that it's impossible to set sixel geometry larger than 800x600 in contour, no matter the window size. Is this intended? It also seems impossible to bring the max sixel geometry back up using `1` (set value) once it's been reduced, though `2` (return to default) does work. Is this intended?

## Environment

Contour Terminal Emulator 0.2.1-unreleased-master-2814f42

## Steps to Reproduce

* To get maximum: `echo -e '\e[?2;4;0S'` result: `2;0;800;600S`
* Try to expand past this maximum: `echo -e 'e[?2;3;900;900S\e[?2;1;0;0S'` result: `2;0;800;600S` (ideally we could make it larger)
* Try to grow after shrinking: `echo -e '\e[?2;3;300;300S\e[?2;1;0;0S\e[?2;3;800;600S\e[?2;1;0;0S'` result: `0;300;300S2;0;300;300S` (ideally we could at least bring this back up to the old size; reset via 2 works)

**Comment by christianparpart** [comment] 2021-09-26 15:23
Hey @dankamongmen 

Did you try to change the limit in the config file already?

https://github.com/contour-terminal/contour/blob/2814f42f705756cd2dbaeb8579618801c714c7fd/src/contour/contour.yml#L23-L34

The `max_width` and `max_height` should actually have an effect here. (At least in my local tests it did) :)

**Comment by dankamongmen** [comment] 2021-09-26 15:27
Yes, that does allow a size up to that in the config file. I gave this bug a bad title. I'd ideally see the two following things:

* I can bring the limit back up to the max with set, just as I can with reset, and
* perhaps even by default, I can configure contour to allow a sixel as large as the current viewing area

i.e. if i pop up a 1000x1000, ideally my max width and max height would be 1000 and 1000 -- i can't effect this using the static config file.

**Comment by christianparpart** [comment] 2021-09-26 15:34
Alright then! Thanks for the ideas. :)

**Comment by dankamongmen** [comment] 2021-09-26 15:50
> Alright then! Thanks for the ideas. :)

the config thing i can either take or leave. the making '1' work ala '2' i'd really appreciate, and ought be substantially more trivial. otherwise, i've got to dig out a special case for you =[.

**Comment by dankamongmen** [comment] 2021-09-26 15:51
> the config thing i can either take or leave. the making '1' work ala '2' i'd really appreciate, and ought be substantially more trivial. otherwise, i've got to dig out a special case for you =[.

put another way, the config thing is a feature request. i regard the other as more of a bugfix, bringing you into line with the published Sixel docs =].

**Comment by christianparpart** [comment] 2021-10-01 13:14
@dankamongmen yo, hey; is https://github.com/contour-terminal/contour/pull/432 precisely the way you expect it?

SetValue works now, but I'm not sure the response is meant to be (didn't test against xterm though, my time's compressed ATM :-) )

**Comment by christianparpart** [comment] 2021-10-01 13:20
> perhaps even by default, I can configure contour to allow a sixel as large as the current viewing area

While I do love the idea, the problem is what if the window size changes. Now I thought what about screen size, but then, what about screen size change. In the end it's just a initial default. But maybe (because it's just a guarding limit), why not just raising the limit to something reasonably higher, say 4k-screen limit-style higher? What do you think?

**Comment by dankamongmen** [comment] 2021-10-01 16:00
> While I do love the idea, the problem is what if the window size changes. Now I thought what about screen size, but then, what about screen size change. In the end it's just a initial default. But maybe (because it's just a guarding limit), why not just raising the limit to something reasonably higher, say 4k-screen limit-style higher? What do you think?

it would be better than what there is now, for sure. this is definitely just a wishlist item.

**Comment by christianparpart** [comment] 2021-10-01 16:20
> > While I do love the idea, the problem is what if the window size changes. Now I thought what about screen size, but then, what about screen size change. In the end it's just a initial default. But maybe (because it's just a guarding limit), why not just raising the limit to something reasonably higher, say 4k-screen limit-style higher? What do you think?
> 
> it would be better than what there is now, for sure. this is definitely just a wishlist item.

But I'd like to have the UX not to be compared with 💩 .
So let's agree that current screen resolution might be the best default as limit (unless configured differently) as I think window sizes may much more frequent than screen size.

**Comment by christianparpart** [comment] 2021-10-02 09:20
> > While I do love the idea, the problem is what if the window size changes. Now I thought what about screen size, but then, what about screen size change. In the end it's just a initial default. But maybe (because it's just a guarding limit), why not just raising the limit to something reasonably higher, say 4k-screen limit-style higher? What do you think?
> 
> it would be better than what there is now, for sure. this is definitely just a wishlist item.

**BAM!** It's weekend and I've merged your point number zwo such that contour will now default to primary screen's display resolution for max image size if nothing is specified (or 0 or below was specified as max width / height).

Enjoy the :sun_with_face:

**Closed by christianparpart** 2021-10-02 09:20 UTC
Labels: bug, enhancement

**Comment by dankamongmen** [comment] 2021-10-02 09:21
awesome!
