### ISSUE TITLE
possible values of hyperlink decoration are undocumented

### ISSUE THREAD

**Issue by ferdinandyb** [contour-terminal/contour#1440] opened 2024-01-29 21:29 UTC
The possible values from discord:

- underline
- dotted-underline
- double-underline
- curly-underline
- dashed-underline
- overline
- crossed-out
- framed
- encircle (i think that one is not realy implemented)

**Comment by Yaraslaut** [comment] 2024-01-29 21:30
Duplicate of https://github.com/contour-terminal/contour/issues/1437 :)

**Closed by Yaraslaut** 2024-01-29 21:30 UTC

**Comment by ferdinandyb** [comment] 2024-01-29 21:45
damn sorry
