### ISSUE TITLE
`ClearHistoryAndReset` action crashes Contour if status line is on

### ISSUE THREAD

**Issue by data-man** [contour-terminal/contour#911] opened 2022-12-13 11:02 UTC
### Contour Terminal version

0.3.8-master-2fe41bba

### Installer source

Github: source code cloned

### Operating System

Devuan Linux (Ceres)

### Architecture

x86-64

### Steps to reproduce

* add  ```- { mods: [Control],        key: L,             action: ClearHistoryAndReset }``` to config
* press `Control+Alt+.`
* press `Control+L`

### Expected Behavior

Don't crash.

### Actual Behavior

Contour crashes.

**Comment by christianparpart** [comment] 2022-12-13 12:12
Wiow. nice. Thanks.

**Comment by christianparpart** [comment] 2022-12-13 13:51
What is this Control+Alt+. combo in the reproduction steps?

**Comment by christianparpart** [comment] 2022-12-13 14:02
ok i get it. it's the default binding to toggle the statusline.

**Comment by whisperity** [comment] 2022-12-13 16:00
```
[2022-12-13 17:00:40.808269] [gui.input] Character press event received: Control L
[2022-12-13 17:00:40.808291] [gui.session] executeAction: UNKNOWN ACTION
[2022-12-13 17:00:40.808295] [gui.session] Clearing history and perform terminal hard reset
[2022-12-13 17:00:40.808314] [vt.grid] resize 80x23 -> 80x24 (cursor (0, 0))
[/home/runner/work/contour/contour/src/terminal/Grid.cpp:454] Precondition failed. 0 <= *_margin.vertical.from && *_margin.vertical.to < *pageSize_.lines
[2]    83255 abort      contour debug '*'
```

**Comment by Yaraslaut** [comment] 2022-12-14 11:39
It crashes  on `void Terminal::hardReset()` call at this line
https://github.com/contour-terminal/contour/blob/9093500f1a443e150b5c943e1a3a2fad130e2fd4/src/vtbackend/Terminal.cpp#L1626
It caused by the fact that status line is deleted from the lines and  validation of margins  `*_margin.vertical.to < *pageSize_.lines` fails. 
If i will comment out   `hostWritableStatusLineScreen_.clearScreen();  `and then few times repeat 
```
press Control+Alt+.
press Control+L
```
I will end up with the following situation  
![image](https://user-images.githubusercontent.com/44506630/207585538-945e481f-167a-4360-bfdf-ec5bff093faa.png)
where some lines on the bottom not accessible anymore

**Comment by data-man** [comment] 2022-12-16 15:25
After #914.
Repeat several times:
* press `Control+Alt+.`
* press `Control+L`

The height decreases each time.

**Comment by Utkarsh-khambra** [comment] 2022-12-16 16:07
I am still getting this crash.

**Comment by christianparpart** [comment] 2022-12-16 16:08
> I am still getting this crash.

Interesting. Let me check.

**Comment by Utkarsh-khambra** [comment] 2022-12-16 17:17
Right now just doing `Control + L` triggers the crash for me

**Comment by christianparpart** [comment] 2022-12-18 10:02
I think we can now finally close this, right?

**Comment by data-man** [comment] 2022-12-18 10:36
I have only one question: why does this action turn off the status line?

**Comment by christianparpart** [comment] 2022-12-18 10:39
> I have only one question: why does this action turn off the status line?

Not on master. And not anymore. Reset is actually a hard reset. Check the discussion board.

**Comment by data-man** [comment] 2022-12-18 10:54
> Not on master.

Yes, on master.

**Comment by christianparpart** [comment] 2022-12-18 11:03
> > Not on master.

> Yes, on master.

Sorry, than it's not configured to be initially visible in your configuration file, can that be? Because `RIS` is resetting back to that.

I'm trying to mostly obey to what https://vt100.net/docs/vt510-rm/RIS.html is mandating, at least as much as possible and as much as we've actually implemented the features that need to be reset.

**Comment by data-man** [comment] 2022-12-18 11:19
I meant after pressing `Control+Alt+.` and `Control+L` the status line should be stay on.

**Comment by christianparpart** [comment] 2022-12-18 11:26
> I meant after pressing `Control+Alt+.` and `Control+L` the status line should be stay on.

That's exactly the point. `ClearHistoryAndReset` is currently doing a hard reset, and therfore also resetting the statusline state to its initial state. Hiding it then is therefore intentionally for the `RIS` at least. If `ClearHistoryAndReset` is not meant to do a hard reset, then we must redesign this action. That's what I was trying to induce over at #921.

**Comment by Yaraslaut** [comment] 2023-04-19 18:13
Can we close it ?

**Comment by Yaraslaut** [comment] 2023-07-17 06:35
I suppose I can close it now

**Closed by Yaraslaut** 2023-07-17 06:35 UTC
Labels: bug, crash(-like)
