### ISSUE TITLE
Font resize triggers window to resize/shrink as well but should not

### ISSUE THREAD

**Issue by rockorager** [contour-terminal/contour#1271] opened 2023-10-14 04:06 UTC
### Contour Terminal version

0.4.0-makepkg-4dde40f6f82c

### Installer source

something else (please specify below)

### Operating System

Arch linux

### Architecture

x86-64

### Other Software

Sway

### Steps to reproduce

Open a Contour terminal. Increase the font size repeatedly (Ctrl+shift+'+')

### Expected Behavior

The font size increases/decreases. Contour does not crash.

### Actual Behavior

The font size increases, and the window size decreases. On focus out, the window is resized. Repeated use crashes `contour``

### Additional notes

Demo: https://0x0.st/H4x6.mp4

**Comment by Yaraslaut** [comment] 2023-10-14 09:28
Hm, the reason why window is resized during font size change is the following:
When we change font size we have to options:
 * To change number of characters (columns) in the line to preserve window size.
    * if you want to preserve window size it means that you need to decrease (or increase) number of columns by one, but you can not have fractional number of charachers per line and what is happening is that you need to change size of the window to fit new line width, which is smaller that been before (for increase of font size) and you end up with smaller window 
 * To change window size to preserve number of characters per line.
    * so basically you increase or decrease window with font size change
    
I think that you can make it configurable, how to handle font resize when we decrease or increase font size, i am personally not super happy with current behaviour when we decrease window size on font size increase, and would chose to preserve number of characers and increase window size. 

So i think we need to separate crash on font resize and behaviour on font resize, it would be great if you can reproduce only crash and show us output of `contour debug all` so then we can fix it before next release, and create separate issue for font resize behaviour configuration

**Comment by christianparpart** [comment] 2023-10-25 19:08
Let's start attempting to fix on the potential non-crash behaviour, the fact that the window resizes upon font resize, which it should not. Of course, this can't be perfect then, but we can do padding as it used to work in the past. I'm trying to sort that out :)

**Comment by christianparpart** [comment] 2023-10-26 15:03
I'm closing this now, because the actual topic is fixed and for the other issue you noted, we are having #1309 now. :)

**Closed by christianparpart** 2023-10-26 15:03 UTC
Labels: bug
