### ISSUE TITLE
empty window and   "Precision qualifier" is not supported prior to GLSL version 1.30

### ISSUE THREAD

**Issue by dbpaul** [contour-terminal/contour#407] opened 2021-09-13 03:55 UTC
## Description
an empty window appears, the desktop background shines through
can only be closed
## Environment
ubuntu 20

## Steps to Reproduce

```
> dpkg -i contour-terminfo_0.2.1~develop-2021-09-09-20-49-77cb600f-0ubuntu1~focal_amd64
> dpkg -i contour_0.2.1~develop-2021-09-09-20-49-77cb600f-0ubuntu1~focal_amd64
```
contour
 
```
[error] Superfluous config key found: profiles.main.font.regular
[error] Superfluous config key found: profiles.main.hyperlink_decoration.default
qt5ct: using qt5ct plugin
QOpenGLShader::compile(Vertex): Vertex shader failed to compile with the following errors:
ERROR: 1:1: error(#263) "Precision qualifier" is not supported prior to GLSL version 1.30
ERROR: 1:1: error(#263) "Precision qualifier" is not supported prior to GLSL version 1.30
ERROR: 1:1: error(#263) "Precision qualifier" is not supported prior to GLSL version 1.30
ERROR: 1:1: error(#263) "Precision qualifier" is not supported prior to GLSL version 1.30
ERROR: 1:1: error(#263) "Precision qualifier" is not supported prior to GLSL version 1.30
ERROR: error(#273) 5 compilation errors.  No code generated


*** Problematic Vertex shader source code ***
#line 1
attribute highp vec3 vertexCoord;attribute highp vec2 textureCoord;varying highp vec2 uv;uniform highp mat4 vertexTransform;uniform highp mat3 textureTransform;void main() {   uv = (textureTransform * vec3(textureCoord,1.0)).xy;   gl_Position = vertexTransform * vec4(vertexCoord,1.0);}
***
Could not link shader program:
 "Vertex shader failed to compile with the following errors:\nERROR: 1:1: error(#263) \"Precision qualifier\" is not supported prior to GLSL version 1.30\nERROR: 1:1: error(#263) \"Precision qualifier\" is not supported prior to GLSL version 1.30\nERROR: 1:1: error(#263) \"Precision qualifier\" is not supported prior to GLSL version 1.30\nERROR: 1:1: error(#263) \"Precision qualifier\" is not supported prior to GLSL version 1.30\nERROR: 1:1: error(#263) \"Precision qualifier\" is not supported prior to GLSL version 1.30\nERROR: error(#273) 5 compilation errors.  No code generated\n\n"
QOpenGLShader::compile(Vertex): Vertex shader failed to compile with the following errors:
ERROR: 1:1: error(#263) "Precision qualifier" is not supported prior to GLSL version 1.30
ERROR: 1:1: error(#263) "Precision qualifier" is not supported prior to GLSL version 1.30
ERROR: 1:1: error(#263) "Precision qualifier" is not supported prior to GLSL version 1.30
ERROR: 1:1: error(#263) "Precision qualifier" is not supported prior to GLSL version 1.30
ERROR: 1:1: error(#263) "Precision qualifier" is not supported prior to GLSL version 1.30
ERROR: error(#273) 5 compilation errors.  No code generated
```
the above error continues multiple times
Sorry, no idea about any of this

**Comment by christianparpart** [comment] 2021-09-13 05:06
Hey. Many thanks for your interest and your report. What graphics card model are you having?

**Comment by dbpaul** [comment] 2021-09-13 10:57
inxi -F
```
System:
  Host: rlxc Kernel: 5.11.0-34-generic x86_64 bits: 64 
  Desktop: Cinnamon 4.8.6 Distro: Linux Mint 20.1 Ulyssa 
CPU:
  Topology: 6-Core model: AMD Ryzen 5 1600 bits: 64 type: MT MCP 
  L2 cache: 3072 KiB  
Graphics:
  Device-1: AMD Ellesmere [Radeon RX 470/480/570/570X/580/580X/590] 
  driver: amdgpu v: kernel 
  Display: x11 server: X.Org 1.20.11 driver: amdgpu,ati 
  unloaded: fbdev,modesetting,vesa 
  resolution: 1920x1080~60Hz, 1920x1080~60Hz 
  OpenGL: renderer: AMD Radeon RX 470 Graphics 
  v: 4.6.14756 Core Profile Context 

```

**Comment by christianparpart** [comment] 2021-09-13 18:21
Hey,

would you mind testing out the .deb file as created by Github CI from:

https://github.com/contour-terminal/contour/actions/runs/1230510860 ?

Scroll to the bottom and there you should find the Ubuntu 20.04 .deb file you can download and `dpkg -i path/to/file.deb`.

**Comment by dbpaul** [comment] 2021-09-13 18:31
working fine :+1: 
sudo dpkg -i contour-0.2.1.1513-prerelease-ubuntu_20_04_amd64.deb
```
[error] Superfluous config key found: profiles.main.font.regular
[error] Superfluous config key found: profiles.main.hyperlink_decoration.default
qt5ct: using qt5ct plugin
```
the mouse pointer is a bit off though. It seems to be flickery and sometimes disappearing when inside the contour window.
There is a noticeably difference between the mouse movement inside the window, and the desktop area.

**Comment by christianparpart** [comment] 2021-09-13 19:32
The mouse cursor disappears as soon as you start typing on your keyboard. That is by design (gnome-terminal does that too).

If you don't like that, we could make that a configurable option to disable/enable this behavior.

> the mouse pointer is a bit off though.

Did you mean that mouse visible/hidden issue I just explained?

>  There is a noticeably difference between the mouse movement inside the window, and the desktop area.

This is interesting. Your host seems to be the first one where this is appearing. Can you maybe elaborate on that one so I better understand what that difference in movement is?

And, thanks for testing :)

**Comment by uspasojevic96** [comment] 2021-09-13 19:33
> > the mouse pointer is a bit off though.
> 
> Did you mean that mouse visible/hidden issue I just explained?

I noticed that too long time ago, it's when you want to select text, but I thought that was fixed by now

**Comment by dbpaul** [comment] 2021-09-13 20:00
Typing and cursor is not the issue. 
When the mouse is moved, it appears to flicker. Faster movements are really jumpy
I would say it looks like:
- mouse moves
- the window gets painted over the mouse pointer
- the mouse pointer gets drawn 
- mouse moves
- the window gets painted over the mouse pointer
- the mouse pointer gets drawn
- - mouse moved
.....
whereas in any other window (or gnome terminal) the movement of the pointer appears to be very smooth.

**Comment by dbpaul** [comment] 2021-09-13 20:05
i just did a quick test with top:
moving the mouse outside of the contour window increases the Xorg process to max 3%
moving the mouse inside the contour window increases Xorg to ~17%
I think there might be a problem in the window refresh on mosemove handling - but just guessing.

**Comment by christianparpart** [comment] 2021-09-13 20:13
> moving the mouse inside the contour window increases Xorg to ~17%

This is known and must be addressed. A mouse move is actually hooked up. I'll check if it is trivial to reduce.

> the window gets painted over the mouse pointer


If that is true then it is more likely a bug in Qt. You may want to correlate to another OpenGL terminal rather then gnome-terminal, which is software only. If you have time and enough will, I'd be curious if you have that flicker also on another OpenGL based Terminal (e.g.: kitty, wezterm, alacritty).

I'll keep digging. Many thanks.

**Comment by dbpaul** [comment] 2021-09-13 20:36
just tested alacritty. No measurable increase in top. Also no flickering.
The window-over-pointer drawing was my guess from past experience what part of the issue could be. I have not done any debugging on that ( and wouldnt  know what to do anyway)

**Comment by christianparpart** [comment] 2021-09-13 21:32
> i just did a quick test with top:
moving the mouse outside of the contour window increases the Xorg process to max 3%
moving the mouse inside the contour window increases Xorg to ~17%

This is now addressed in #412 and drops CPU load back to <= 3%.

> I think there might be a problem in the window refresh on mose-move handling - but just guessing.

A mouse-move forced the screen to be rerendered, even if there are no changes. That's not the case anymore (with the above PR that isn't on master just yet, but the CI creates binaries for early testing, just in case). :)

**Comment by christianparpart** [comment] 2021-09-13 21:37
So I think the only thing left in this (collective) ticket is the fact that the mouse seems to "flicker" sometimes, right? I tried to repro that locally, but sadly the only flicker I noticed did look like a jumpy mouse instead, and that happens everywhere on my screen no matter what app I am using. I can try on my desktop machine once being back from vacation (by the end of this week). Do you (or @uspasojevic96 ?) think you can create a tiny video (/animated gif / embedded mpg here) showing me that? is that catch-able by screen recording software? I generally had good experience with `peek` program for showcasing GUI stuff.

**Comment by dbpaul** [comment] 2021-09-14 08:01
sudo dpkg -i contour-0.2.1.1526-prerelease-ubuntu_20_04_amd64.deb
- mouse movement is much smoother, i would say flickering is gone
- I still think that the mouse movement is jumpier inside the window, especially when moving the mouse in the y axis. But that could be some sort of confirmation bias or higher cpu load
- still much higher Xorg cpu load. I would say unchanged from before ~17%. Did I use a wrong build?

Already tried to use simplescreenrecorder yesterday. at 30fps not enough mouse pointers were captured, at 60fps mouse movement was smooth everywhere :( But as flickering is gone, this is a bit moot now anyway.

**Comment by christianparpart** [comment] 2021-09-14 12:07
> still much higher Xorg cpu load. I would say unchanged from before ~17%. Did I use a wrong build?

Build 1526 is just fine. But i was actually reducing CPU load of `contour` itself. I did not even look at Xorg process's load, lol.

I try to investigate on that one, too. Can't promise any immediate magic though. :)

**Comment by christianparpart** [comment] 2021-09-15 06:42
@dbpaul Hey, I've now also done some more perf optimizations that should affect cursor (!) rendering as well as `Xorg` process util.

Would you mind giving this a try and report back then? :-)

**Comment by dbpaul** [comment] 2021-09-16 16:32
contour-0.2.1.1541-prerelease-ubuntu_20_04_amd64.deb
smooth movement, no flickering, no jumpiness.
Also no measurable cpu load increase, 

looks fine to me!

**Comment by christianparpart** [comment] 2021-09-16 18:54
Perfect, many many thanks for your continued patience for a project at this early stage.

Enjoy :+)

**Closed by christianparpart** 2021-09-16 18:54 UTC
Labels: bug, frontend: OpenGL, crash
