### ISSUE TITLE
Looks bad compared to Alacritty :(

### ISSUE THREAD

**Issue by nyngwang** [contour-terminal/contour#609] opened 2022-02-19 00:01 UTC
The font I'm using is:

```
Fantasque Sans Mono Nerd Font
```

Did you really support nerd font? And I cannot search it from homebrew.

<img src="https://user-images.githubusercontent.com/24765272/154776358-0389b885-eb31-452c-89ba-1ce44eb96cbc.png" width="600">

**Comment by christianparpart** [comment] 2022-02-19 08:44
If you're installing from a pre-built version, you might want to try [contour-0.3.0.2777-2777-osx.dmg](https://github.com/contour-terminal/contour/suites/5367877731/artifacts/168357433). Does **this** version also cause problems for you?

**Comment by uspasojevic96** [comment] 2022-02-19 09:22
Can you try setting `locator` to `fontconfig` and `text_shaping` to `OpenShaper`?

**Comment by nyngwang** [comment] 2022-02-21 02:50
@christianparpart @uspasojevic96 Sorry for my late reply! Let me check this now!

**Comment by christianparpart** [comment] 2022-02-21 07:37
> @christianparpart @uspasojevic96 Sorry for my late reply! Let me check these now!
> 
> update:
> 
> > [...] to try [contour-0.3.0.2777-2777-osx.dmg](https://github.com/contour-terminal/contour/suites/5367877731/artifacts/168357433). Does this version also cause problems for you?
> 
> Yes, I got:
> 
> <img alt="" width="600" src="https://user-images.githubusercontent.com/24765272/154881295-f53d7ed0-ff19-4bd1-a0f7-d15965fbcc09.png">

If I'm not mistaken, this screenshot now looks much better than your first one. So is this considered solved then from your point of view? Or do you think there are still pixel artifacts (bad resolution)?

Another thing: I see you have a rectangular box between the time column and the filename column. That looks like there's a missing glyph. What should have been displayed there? Do you (by accident) happen to know the codepoint or can send me an expectation-screenshot?

Many thanks, and have an awesome Monday,
Christian.

**Comment by nyngwang** [comment] 2022-02-22 12:01
> If I'm not mistaken, this screenshot now looks much better than your first one. [...]

Yes, this is the beautiful part :)

> Another thing: I see you have a rectangular box between the time column and the filename column. [...]

(Forgive my quoting my OP again):

> Did you really support **nerd font**? [...]

The nerd font I used downloaded from [here](https://www.google.com/search?q=github+nerdfont&oq=github+nerdfont+&aqs=edge..69i57j0i10i512l8.3885j0j1&sourceid=chrome&ie=UTF-8), where they call those icons _glyphs_.

> [...] or can send me an expectation-screenshot?

I should not forget this important information. Here is it:

<img src="https://user-images.githubusercontent.com/24765272/155127870-dd6213bb-ab25-4074-bbc8-dcc05a669b51.png" width="400">

**Comment by uspasojevic96** [comment] 2022-02-23 09:41
@nyngwang I would still like you to try to change font locator as that might be the issue, currently CoreText is experimental

**Comment by nyngwang** [comment] 2022-02-23 12:09
@uspasojevic96: I'm new to configuration. Where can I set/change the font? What does it mean "font locator" ?

**Comment by uspasojevic96** [comment] 2022-02-23 12:30
@nyngwang in `~/.config/contour/contour.yaml` there is `locator` property (you can text search it), which should have `native` value by default, can you change it to `fontconfig`?

**Comment by christianparpart** [comment] 2022-02-23 13:28
> @uspasojevic96: I'm new to configuration. Where can I set/change the font? What does it mean "font locator" ?

That motivates me even more that the out-of-the-box experience should always rock as much as possible.

**Comment by nyngwang** [comment] 2022-02-23 14:34
@christianparpart, @uspasojevic96: Happy news: I made it works. But I found another serious problem: Every time I tried "command q" to quit Contour, it becomes __not responding__:

<img src="https://user-images.githubusercontent.com/24765272/155340194-d5720fc0-a40b-4d61-abdf-2c2f4aa967ef.png" width="600">

**Comment by uspasojevic96** [comment] 2022-02-23 14:35
@nyngwang that is known issue, fix is waiting to be merged into master from edge

**Comment by nyngwang** [comment] 2022-02-23 14:39
@uspasojevic96 How to disable ligature btw? It seems that it is enabled by default?

**Comment by uspasojevic96** [comment] 2022-02-23 14:41
> @uspasojevic96 How to disable ligature btw? It seems that it is enabled by default.
> 
> No

there is currently no way to disable them iirc

@christianparpart FYI

**Comment by nyngwang** [comment] 2022-02-23 14:45
> there is currently no way to disable them iirc

It's OK. The last issue I think you _need_ to consider is that in Alacritty I can change the font size via "command +" and "command -".

Do we have this feature? If so, how can I customize the shortcut to make it works via "command +/-", which I have got used t?.

**Comment by uspasojevic96** [comment] 2022-02-23 14:49
use `Control` instead of `Command` for now due to Qt being dumb

**Comment by nyngwang** [comment] 2022-02-23 14:51
@uspasojevic96 Strangely, I made it work by `Ctrl + Shift` :/ ?

btw I will rate you 10/10 on sale support aspect.

**Comment by uspasojevic96** [comment] 2022-02-23 15:00
@christianparpart resize/reflow bug?

**Comment by christianparpart** [comment] 2022-03-13 13:28
@nyngwang Hey. I think the bad texture quality that made your font look more ugly is fixed now since quite a while. I was now trying to check if I can close this ticket and found your last video (sorry for the delay, i was busy with IRL apparently). And I was trying to reproduce what you have been demo'ing in your video. It seems like I have fixed that already too.

Can you confirm that?

Enjoy the sunny Sunday. ;)
Christian.

**Comment by nyngwang** [comment] 2022-03-13 22:49
Yes, I can we can close it now~

**Closed** 2022-03-14 06:08 UTC
Labels: bug, fonts, platform: osx
