### ISSUE TITLE
Wrong placement of cursor after exit from `screen`

### ISSUE THREAD

**Issue by Yaraslaut** [contour-terminal/contour#897] opened 2022-12-09 20:11 UTC
### Contour Terminal version

Contour Terminal Emulator 0.3.5-master-6e047fd9

### Installer source

Github: source code cloned

### Operating System

Manjaro Linux

### Architecture

x86-64

### Other Software

Screen version 4.09.00 (GNU) 30-Jan-22

### Steps to reproduce

https://user-images.githubusercontent.com/44506630/206787815-f2a35ed9-9eed-4379-a409-be7fd4f14c24.mp4

### Expected Behavior

Similar to tmux

### Actual Behavior

Cursor is placed on second line from the top of the window

### Additional notes
vt trace
```
[2022-12-10 13:35:42.196238] [vt.trace.sequence] control U+0D (Carriage Return)
[2022-12-10 13:35:42.196272] [vt.trace.sequence] control U+0A (Line Feed)
[2022-12-10 13:35:42.200540] [vt.trace.sequence] Handle VT sequence: CSI ? 1 l
[2022-12-10 13:35:42.200579] [vt.trace.sequence] Handle VT sequence: ESC >
[2022-12-10 13:35:42.200598] [vt.trace.sequence] Handle VT sequence: CSI 28;1 H
[2022-12-10 13:35:42.200613] [vt.trace.sequence] control U+0D (Carriage Return)
[2022-12-10 13:35:42.200623] [vt.trace.sequence] control U+0A (Line Feed)
[2022-12-10 13:35:42.200639] [vt.trace.sequence] Handle VT sequence: CSI ? 1049 l
[2022-12-10 13:35:42.200873] [vt.trace.sequence] Handle VT sequence: CSI 23;0;0 t
```

**Comment by whisperity** [comment] 2022-12-09 20:52
Is this Contour-specific? A quick guess from my end is that the problem is not the cursor placement *per se*, but the fact that the existing buffer is not wiped. I guess screen is dumb enough to always reposition the exit to the top left corner first.

I tried the same ordeal in PuTTY, and right now I get the existing buffer properly cleaned, and the cursor properly placed on the line after the `[screen is terminating]` printout.

https://user-images.githubusercontent.com/1969470/206794000-f7213cf8-13b0-427e-839e-24690edd46a4.mp4

 * What happens with tmux?
 * Are you using a multiline prompt?

**Comment by Yaraslaut** [comment] 2022-12-09 21:02
This is what is happening for  `tmux`. So, everything is alright 

https://user-images.githubusercontent.com/44506630/206795269-6d0858a9-1427-4708-8317-e6f9a9da961f.mp4

Another terminals (for example `gnome terminal`) handle `screen` the same way as `tmux`

https://user-images.githubusercontent.com/44506630/206795435-c357765a-945d-4f4e-8b46-e161c2199b2c.mp4

**Comment by christianparpart** [comment] 2022-12-10 20:15
This should be fixed by having the TERM environment variable set to `contour`. Can you confirm that?

**Comment by Utkarsh-khambra** [comment] 2022-12-10 21:49
So I checked what sequences `screen` invoke after running and it seems that for TERM=xterm-256color, screen also invokes `soft reset` which for contour among other things also resets the cursor to origin.

**Comment by christianparpart** [comment] 2022-12-11 19:16
I safely assume that we can close this one now, right? :) Just re-open if I'm terribly mistaken.

**Closed by christianparpart** 2022-12-11 19:16 UTC
Labels: bug, VT: Backend, frontend
