### ISSUE TITLE
possible problems in sixel implementation

### ISSUE THREAD

**Issue by dankamongmen** [contour-terminal/contour#588] opened 2022-01-15 19:54 UTC
### Contour Terminal version

0.3.0-unreleased-master-115721fc

### Installer source

Github: source code cloned

### Operating System

Debian Linux Unstable

### Architecture

x86-64

### Other Software

Notcurses 3.0.4

### Steps to reproduce

Run `notcurses-demo k` in contour.

### Expected Behavior

![2022-01-15-145120_884x556_scrot](https://user-images.githubusercontent.com/143473/149635863-015163c8-0277-4280-8e17-e8c4674c2696.png)
 

XTerm output

### Actual Behavior

![2022-01-15-145232_906x660_scrot](https://user-images.githubusercontent.com/143473/149635887-c5bf1b9b-1937-4b27-9cd0-aecf8a81707e.png)

### Additional notes

This might very well be my bug, my friend. I didn't think it was, but running `ncplayer ../data/covid19.jpg` on Contour looks just fine:

![2022-01-15-145325_906x660_scrot](https://user-images.githubusercontent.com/143473/149635903-f2302576-5c1b-4d8a-b9e5-d0518cd0592c.png)

so I might be doing something stupid in the `[keller]` demo? This problem doesn't show up in any other Sixel terminals, but that doesn't mean it's your fault. I'll look into this on my side (I'll create an issue and link these two), but if you think of anything obvious on your side, let me know.

**Comment by dankamongmen** [comment] 2022-01-15 19:55
you know, the weridness we see in the Contour example looks very much like sextant residue, which would have been the immediately preceding image (`[keller]` steps through various blitters).

**Comment by dankamongmen** [comment] 2022-01-15 19:57
ok, i can reproduce this if i do `ncplayer -bsex ../data/covid19.jpg` (in Contour) and then press '6' to switch to pixel blitting:

![2022-01-15-145726_906x660_scrot](https://user-images.githubusercontent.com/143473/149635995-c18eb7e7-6606-4b4d-bdfa-1a8118902158.png)

**Comment by dankamongmen** [comment] 2022-01-15 20:03
looking into this a bit more deeply, it looks like your issue. if i fling up a bunch of sextants, and then draw a sixel atop them in contour, i get the weird corruption seen above, on pretty much arbitrary images.

**Comment by christianparpart** [comment] 2022-01-15 21:03
After a long life of being honest, finally being corrupt.

Ok, j/k. If it is a visual corruption of sixels when sextants have been drawn below(?) Before, there may be a correlation. I assume your image is not transparent, right? I have to look into this. (Btw, I am refactoring rendering currently in order to satisfy the notcurses Unicode demo much better anyways. I hope I will find and reproduce what you describe).


Thanks.

**Comment by christianparpart** [comment] 2022-01-15 21:08
> ok, i can reproduce this if i do `ncplayer -bsex ../data/covid19.jpg` (in Contour) and then press '6' to switch to pixel blitting:
> 
> ![2022-01-15-145726_906x660_scrot](https://user-images.githubusercontent.com/143473/149635995-c18eb7e7-6606-4b4d-bdfa-1a8118902158.png)
> 

Stupid question. What do you internally do when you switch from sextant to Sixel?

Do you just repaint or do you clear the screen before. 
2. Is output synchronization active?

**Comment by christianparpart** [comment] 2022-01-16 10:04
@dankamongmen Hey. It seems like my workstation PC is vaccinated. I can't run the `keller` demo as it says "SKIPPED". I checked the cmake config and didn't find anything particular disabled. What am I missing here?

**Comment by christianparpart** [comment] 2022-01-16 10:13
@dankamongmen btw, haha, I just realized. You do not seem to clear the page before rerendering in `ncplay` from Sexel to Sixels. I have a little shortcut I can press to dump the internal state:

```yml
input_mapping:
- { mods: [Control, Alt],   key: P,             action: WriteScreen, chars: '\e]888\e\\' }
- ...
```


<details>
<summary> While I see the Sixels on the terminal window in question itself, the printed dump of the calling terminal will show the Sexels, which looks like this (click me):
 </summary>

![image](https://user-images.githubusercontent.com/56763/149655656-e485bfd9-20b8-41fc-ac16-d08dd1638ad9.png)

</details>

So while `ncplayer` works, I still sadly can't run the `keller` demo. ;(

Details however is, if a sixel fragment in a grid cell cannot be rendered, you see the text underneath (if any). that is why your screenshot may look a little but wonky.

And the reason for that may be my poor LRU cache (and maybe) implementation. But this is (hopefully) about to improve in #572 (most likely it will).

**Comment by christianparpart** [comment] 2022-01-24 15:52
Hashing changed significantly in #572 and I cannot reproduce this anymore. I used to be able to on master branch. So I might consider this one fixed once the referenced PR is merged and you could confirm this also. :)

**Comment by christianparpart** [comment] 2022-03-18 11:00
@dankamongmen I think we can close this. At least AI can't reproduce anymore since quite some time.

**Closed by christianparpart** 2022-03-18 11:00 UTC
Labels: bug
